Adding new version of flutter_lint 2.0.1 and adding needRepaint on [AdaptiveHeightSliverPersistentHeader] widget.
camillobucciarelli/persistent_header_adaptive pull request #1
Opened 2023-05-17 04:17 UTC by luanbatistadev

was added some new rules to analysis_options.yaml to dart 2.19 or higher
was added too a new parameter to AdaptiveHeightSliverPersistentHeader widget, [needRepaint] because in some case is necessary repaint widget inside it. 
thanks for your package, it help me so much. 
att, Luan Batista - Mobile Software Engineer at Evolve - Cimed Remédios S.A. - Brazil.

2023-05-20 11:23 UTC, camillobucciarelli commented
Thank you for your contribution.

if you clean comments in analysis option I merge it

2023-05-20 15:02 UTC, luanbatistadev commented
okok, i will it. tnx

2023-05-23 06:31 UTC, camillobucciarelli requested changes

2023-05-23 06:31 UTC, camillobucciarelli commented on lib/size_reporting_widget.dart
> +  final ValueChanged<Size> onSizeChange;
I prefer to maintain the order as previously, change lint if necessary

2023-05-23 06:31 UTC, camillobucciarelli commented on pubspec.yaml
> +  flutter: ">=3.10.1"
Why you would like to force to flutter 3.10.1? I prefer to support the last 3 versions, you can bump to 3.3.0 at least

2023-05-23 06:31 UTC, camillobucciarelli commented on lib/overflow_widget.dart
> +  final Alignment alignment;
I prefer to maintain the order as previously, change lint if necessary

2023-05-23 06:31 UTC, camillobucciarelli commented on lib/adaptive_height_sliver_persistent_header.dart
> +  final bool needRepaint;
I prefer to maintain the order as previously, change lint if necessary

2023-05-23 06:31 UTC, camillobucciarelli commented on lib/adaptive_height_delegate.dart
> +  double height;
I prefer to maintain the order as previously, change lint if necessary

2023-05-23 06:31 UTC, camillobucciarelli commented on example/pubspec.yaml
> +
I prefer to maintain the order as previously, change lint if necessary

2023-05-23 06:31 UTC, camillobucciarelli commented on pubspec.yaml
>      sdk: flutter
I prefer to maintain the order as previously, change lint if necessary

2023-08-23 14:32 UTC, merged